steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud app deploy --quiet --project=${_PROJECT_ID} \
    --version=${SHORT_SHA} \
    --no-promote
  secretEnv: ['TELEGRAM_BOT_TOKEN']

options:
  logging: CLOUD_LOGGING_ONLY  # Esta linha resolve o erro

substitutions:
  _PROJECT_ID: bot-telegram-468202

availableSecrets:
  secretManager:
  - versionName: projects/bot-telegram-468202/secrets/TELEGRAM_BOT_TOKEN/versions/latest
    env: 'TELEGRAM_BOT_TOKEN'
