steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "Iniciando deploy..."
    gcloud app deploy app.yaml --quiet --project=${_PROJECT_ID} \
    --version=${SHORT_SHA} \
    --no-promote
    echo "Deploy concluído"
  secretEnv: ['TELEGRAM_BOT_TOKEN']
  id: 'deploy'

options:
  logging: CLOUD_LOGGING_ONLY  # Solução principal para o erro
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET  # Solução alternativa

availableSecrets:
  secretManager:
  - versionName: projects/${_PROJECT_ID}/secrets/TELEGRAM_BOT_TOKEN/versions/latest
    env: 'TELEGRAM_BOT_TOKEN'

substitutions:
  _PROJECT_ID: 'bot-telegram-468202'  # Substitua pelo seu ID real
